name: easter
version: 1.0.0+3

description: A small Dart package that calculates the date of Easter from 1583 to 4099.
author: Nikolaj Hesselholt Skov <nikolajhesselholtskov@gmail.com>
homepage: https://github.com/nikolajskov/easter

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
